name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main  # Add main branch to trigger on push
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

  sync-main:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Trigger on push to main

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Sync Develop with Main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the PAT token
      run: |
        git fetch origin
        git checkout main
        git merge origin/develop --allow-unrelated-histories
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/cheehonghsia/user-service.git main