name: Deploy to Main with PR

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots clean install

    - name: Run tests
      run: mvn test

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge develop into main
      run: |
        git checkout main
        git merge develop --allow-unrelated-histories
        git push origin main

    - name: Merge develop into main
      env:
        ACTIONS_DEPLOY_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
      run: |
        git checkout main
        git merge develop --allow-unrelated-histories
        git push https://github-actions:${{ secrets.ACTIONS_DEPLOY_TOKEN }}@github.com/cheehonghsia/user-service.git main

    - name: Update develop with latest main
      env:
        ACTIONS_DEPLOY_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
      run: |
        git checkout develop
        git merge main --allow-unrelated-histories
        git push https://github-actions:${{ secrets.ACTIONS_DEPLOY_TOKEN }}@github.com/cheehonghsia/user-service.git develop