name: Deploy to Main with PR

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots clean install

    - name: Run tests
      run: mvn test

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge develop into main
      run: |
        git checkout main
        git merge develop
        git push origin main