name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

# Add this permissions block
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin' # You can also use 'zulu', 'adopt', etc.

    - name: Build with Maven
      run: mvn clean install

    - name: Update Main Branch
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git fetch origin
        git checkout -B main origin/main
        git merge --allow-unrelated-histories origin/develop
        git push origin main
