name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      id: cpr
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Merge develop into main
        title: Merge develop into main
        body: |
          This PR was automatically created to merge changes from develop into main.
          It will be automatically merged if all checks pass.
        branch: auto-pr-develop-to-main
        base: main

    - name: Auto-merge PR
      if: steps.cpr.outputs.pull-request-number
      run: |
        gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --auto --merge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update develop
      if: success()
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout develop
        git pull origin develop
        git merge origin/main
        git push origin develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
