name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin' # You can also use 'zulu', 'adopt', etc.

    - name: Build with Maven
      run: mvn clean install

    - name: Run Checkstyle
      run: mvn checkstyle:check

    - name: Deploy to Main
      if: success()
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout main
        git merge develop
        git push origin main
